default: &default
  suspicious_domains:
    # NOTE: These domains are considered suspicious by GDS corporate IT
    #       making requests from the corporate network may raise flags.
    - nostringsng.com
    - www.becauseiamagirl.org
    - www.bilebrizoua.ci
    # NOTE: This is not a comprehensive list of all suspicious domains on the internet.

test:
  <<: *default
  suspicious_domains:
    - malicious.example.com

development:
  <<: *default

production:
  <<: *default
